#!/bin/bash
#PBS -N evaluate_mbert
#PBS -q workq
#PBS -l nodes=1:ppn=2
#PBS -l walltime=02:00:00
#PBS -l mem=4gb
#PBS -o localhost:$HOME/NLPScholar/final/logs/evaluate.out
#PBS -e localhost:$HOME/NLPScholar/final/logs/evaluate.err
#PBS -m bae
#PBS -M mxgonzalez@colgate.edu
#PBS -V

cd $PBS_O_WORKDIR
cd $HOME/NLPScholar/final

source /local/JupyterHub/bin/activate && conda activate nlp

python /home/NLPScholar/main.py config_files/evaluate.yaml
